syntax = "proto3";
package gamma.onehub.api.v1.types;

enum CallState {
  CALL_STATE_UNSPECIFIED = 0;
  CALL_STATE_PROVISIONAL = 1;
  CALL_STATE_RINGING = 3;
  CALL_STATE_RING_BACK = 4;
  CALL_STATE_CONNECTED = 5;
  CALL_STATE_PARKED = 6;
  CALL_STATE_CONSULT = 7;
  CALL_STATE_CONFERENCE_ACTIVE = 8;
  CALL_STATE_CONFERENCE_INACTIVE = 9;
  CALL_STATE_CONFERENCE_CONSULT = 10;
  CALL_STATE_VOICEMAIL_LINKED = 11;
  CALL_STATE_VOICEMAIL_MAIN = 12;
  CALL_STATE_CALL_BACK_ON_BUSY = 13;
  CALL_STATE_LOGIN_LOGOUT = 14;
  CALL_STATE_MUSIC_ON_HOLD_TEST = 15;
}
